with __dbt__cte__washington_counties as (


SELECT *
FROM (VALUES ('AD', 'Adams'),
             ('AS', 'Asotin'),
             ('BE', 'Benton'),
             ('CH', 'Chelan'),
             ('CM', 'Clallam'),
             ('CR', 'Clark'),
             ('CU', 'Columbia'),
             ('CZ', 'Cowlitz'),
             ('DG', 'Douglas'),
             ('FE', 'Ferry'),
             ('FR', 'Franklin'),
             ('GA', 'Garfield'),
             ('GR', 'Grant'),
             ('GY', 'Grays Harbor'),
             ('IS', 'Island'),
             ('JE', 'Jefferson'),
             ('KI', 'King'),
             ('KP', 'Kitsap'),
             ('KS', 'Kittitas'),
             ('KT', 'Klickitat'),
             ('LE', 'Lewis'),
             ('LI', 'Lincoln'),
             ('MA', 'Mason'),
             ('OK', 'Okanogan'),
             ('PA', 'Pacific'),
             ('PE', 'Pend Oreille'),
             ('PI', 'Pierce'),
             ('SJ', 'San Juan'),
             ('SK', 'Skagit'),
             ('SM', 'Skamania'),
             ('SN', 'Snohomish'),
             ('SP', 'Spokane'),
             ('ST', 'Stevens'),
             ('TH', 'Thurston'),
             ('WK', 'Wahkiakum'),
             ('WL', 'Walla Walla'),
             ('WM', 'Whatcom'),
             ('WT', 'Whitman'),
             ('YA', 'Yakima')) AS A (COUNTY_CODE, COUNTY_NAME)
) SELECT '2023-09-01'::date                      as FILE_DATE,
       'WA'                                    as STATE_CODE,
       C.COUNTY_NAME                           as COUNTY_CODE,
       STATE_VOTER_ID                          AS VOTER_ID,
       NULL                                    AS PREFIX,
       F_NAME                                  AS FIRST_NAME,
       M_NAME                                  AS MIDDLE_NAME,
       L_NAME                                  AS LAST_NAME,
       NAME_SUFFIX                             AS NAME_SUFFIX,
       PUBLIC.MERGE_ADDRESS_ELEMENTS([
           REG_ST_NUM, REG_ST_FRAC,
           REG_ST_PRE_DIRECTION,
           REG_ST_NAME,
           REG_ST_TYPE,
           REG_ST_POST_DIRECTION ])            AS RESIDENCE_ADDRESS_LINE_1,
       PUBLIC.MERGE_ADDRESS_ELEMENTS([
           REG_UNIT_TYPE, REG_ST_UNIT_NUM ])   AS RESIDENCE_ADDRESS_LINE_2,
       REG_CITY                                AS RESIDENCE_ADDRESS_CITY,
       COALESCE(REG_STATE, 'WA')               AS RESIDENCE_ADDRESS_STATE,
       REG_ZIP_CODE                            AS RESIDENCE_ADDRESS_ZIPCODE,
       'USA'                                   AS RESIDENCE_ADDRESS_COUNTRY,
       BIRTHYEAR                               AS BIRTH_YEAR,
       NULL                                    AS BIRTH_MONTH,
       NULL                                    AS BIRTH_DATE,
       CASE
           WHEN STATUS_CODE = 'Active' THEN 'A'
           WHEN STATUS_CODE = 'Inactive' THEN 'I'
           ELSE STATUS_CODE END                as VOTER_STATUS,
       TO_DATE(REGISTRATIONDATE, 'YYYY-MM-DD') AS REGISTRATION_DATE,
       TO_DATE(LAST_VOTED, 'YYYY-MM-DD')       AS LAST_VOTED_DATE,
       NULL                                    AS LAST_PARTY_VOTED,
       CONGRESSIONAL_DISTRICT                  AS CONGRESSIONAL_DISTRICT,
       NULL                                    AS STATE_SENATE_DISTRICT,
       LEGISLATIVE_DISTRICT                    AS STATE_HOUSE_DISTRICT,
       NULL                                    AS JUDICIAL_DISTRICT,
       NULL                                    AS COUNTY_COMMISSION_DISTRICT,
       NULL                                    AS SCHOOL_BOARD_DISTRICT,
       NULL                                    AS CITY_COUNCIL_DISTRICT,
       PRECINCT_CODE                           AS COUNTY_PRECINCT,
       NULL                                    AS MUNICIPAL_PRECINCT,
       NULL                                    AS RACE,
       NULL                                    AS GENDER,
       MAIL1                                   AS MAILING_ADDRESS_LINE_1,
       MAIL2                                   AS MAILING_ADDRESS_LINE_2,
       MAIL3                                   AS MAILING_LINE_3,
       MAIL_CITY                               AS MAILING_CITY,
       MAIL_STATE                              AS MAILING_STATE,
       MAIL_ZIP                                AS MAILING_ZIPCODE,
       MAIL_COUNTRY                            AS MAILING_COUNTRY
FROM DBT_VOTER_DATA.raw.WASHINGTON_VOTERS_2023_09_01 V
         INNER JOIN __dbt__cte__washington_counties C ON V.COUNTY_CODE = C.COUNTY_CODE