

SELECT *
FROM (VALUES ('AD', 'Adams'),
             ('AS', 'Asotin'),
             ('BE', 'Benton'),
             ('CH', 'Chelan'),
             ('CM', 'Clallam'),
             ('CR', 'Clark'),
             ('CU', 'Columbia'),
             ('CZ', 'Cowlitz'),
             ('DG', 'Douglas'),
             ('FE', 'Ferry'),
             ('FR', 'Franklin'),
             ('GA', 'Garfield'),
             ('GR', 'Grant'),
             ('GY', 'Grays Harbor'),
             ('IS', 'Island'),
             ('JE', 'Jefferson'),
             ('KI', 'King'),
             ('KP', 'Kitsap'),
             ('KS', 'Kittitas'),
             ('KT', 'Klickitat'),
             ('LE', 'Lewis'),
             ('LI', 'Lincoln'),
             ('MA', 'Mason'),
             ('OK', 'Okanogan'),
             ('PA', 'Pacific'),
             ('PE', 'Pend Oreille'),
             ('PI', 'Pierce'),
             ('SJ', 'San Juan'),
             ('SK', 'Skagit'),
             ('SM', 'Skamania'),
             ('SN', 'Snohomish'),
             ('SP', 'Spokane'),
             ('ST', 'Stevens'),
             ('TH', 'Thurston'),
             ('WK', 'Wahkiakum'),
             ('WL', 'Walla Walla'),
             ('WM', 'Whatcom'),
             ('WT', 'Whitman'),
             ('YA', 'Yakima')) AS A (COUNTY_CODE, COUNTY_NAME)