WITH  __dbt__cte__ohio_counties as (



SELECT *
FROM (VALUES (1, 'Adams'),
             (2, 'Allen'),
             (3, 'Ashland'),
             (4, 'Ashtabula'),
             (5, 'Athens'),
             (6, 'Auglaize'),
             (7, 'Belmont'),
             (8, 'Brown'),
             (9, 'Butler'),
             (10, 'Carroll'),
             (11, 'Champaign'),
             (12, 'Clark'),
             (13, 'Clermont'),
             (14, 'Clinton'),
             (15, 'Columbiana'),
             (16, 'Coshocton'),
             (17, 'Crawford'),
             (18, 'Cuyahoga'),
             (19, 'Darke'),
             (20, 'Defiance'),
             (21, 'Delaware'),
             (22, 'Erie'),
             (23, 'Fairfield'),
             (24, 'Fayette'),
             (25, 'Franklin'),
             (26, 'Fulton'),
             (27, 'Gallia'),
             (28, 'Geauga'),
             (29, 'Greene'),
             (30, 'Guernsey'),
             (31, 'Hamilton'),
             (32, 'Hancock'),
             (33, 'Hardin'),
             (34, 'Harrison'),
             (35, 'Henry'),
             (36, 'Highland'),
             (37, 'Hocking'),
             (38, 'Holmes'),
             (39, 'Huron'),
             (40, 'Jackson'),
             (41, 'Jefferson'),
             (42, 'Knox'),
             (43, 'Lake'),
             (44, 'Lawrence'),
             (45, 'Licking'),
             (46, 'Logan'),
             (47, 'Lorain'),
             (48, 'Lucas'),
             (49, 'Madison'),
             (50, 'Mahoning'),
             (51, 'Marion'),
             (52, 'Medina'),
             (53, 'Meigs'),
             (54, 'Mercer'),
             (55, 'Miami'),
             (56, 'Monroe'),
             (57, 'Montgomery'),
             (58, 'Morgan'),
             (59, 'Morrow'),
             (60, 'Muskingum'),
             (61, 'Noble'),
             (62, 'Ottawa'),
             (63, 'Paulding'),
             (64, 'Perry'),
             (65, 'Pickaway'),
             (66, 'Pike'),
             (67, 'Portage'),
             (68, 'Preble'),
             (69, 'Putnam'),
             (70, 'Richland'),
             (71, 'Ross'),
             (72, 'Sandusky'),
             (73, 'Scioto'),
             (74, 'Seneca'),
             (75, 'Shelby'),
             (76, 'Stark'),
             (77, 'Summit'),
             (78, 'Trumbull'),
             (79, 'Tuscarawas'),
             (80, 'Union'),
             (81, 'Van Wert'),
             (82, 'Vinton'),
             (83, 'Warren'),
             (84, 'Washington'),
             (85, 'Wayne'),
             (86, 'Williams'),
             (87, 'Wood'),
             (88, 'Wyandot')) AS A (county_id, county_name)
), OHIO_VOTER_HISTORY AS (SELECT COUNTY_NUMBER,
                                   SOS_VOTERID,
                                   ELECTION_CODE,
                                   VOTE_TYPE_CODE
                            FROM DBT_VOTER_DATA.raw.OHIO_VOTERS_2023_09_25 UNPIVOT (VOTE_TYPE_CODE FOR ELECTION_CODE IN (PRIMARY_2000_03_07,
                                GENERAL_2000_11_07,
                                SPECIAL_2001_05_08,
                                GENERAL_2001_11_06,
                                PRIMARY_2002_05_07,
                                GENERAL_2002_11_05,
                                SPECIAL_2003_05_06,
                                GENERAL_2003_11_04,
                                PRIMARY_2004_03_02,
                                GENERAL_2004_11_02,
                                SPECIAL_2005_02_08,
                                PRIMARY_2005_05_03,
                                PRIMARY_2005_09_13,
                                GENERAL_2005_11_08,
                                SPECIAL_2006_02_07,
                                PRIMARY_2006_05_02,
                                GENERAL_2006_11_07,
                                PRIMARY_2007_05_08,
                                PRIMARY_2007_09_11,
                                GENERAL_2007_11_06,
                                PRIMARY_2007_11_06,
                                GENERAL_2007_12_11,
                                PRIMARY_2008_03_04,
                                PRIMARY_2008_10_14,
                                GENERAL_2008_11_04,
                                GENERAL_2008_11_18,
                                PRIMARY_2009_05_05,
                                PRIMARY_2009_09_08,
                                PRIMARY_2009_09_15,
                                PRIMARY_2009_09_29,
                                GENERAL_2009_11_03,
                                PRIMARY_2010_05_04,
                                PRIMARY_2010_07_13,
                                PRIMARY_2010_09_07,
                                GENERAL_2010_11_02,
                                PRIMARY_2011_05_03,
                                PRIMARY_2011_09_13,
                                GENERAL_2011_11_08,
                                PRIMARY_2012_03_06,
                                GENERAL_2012_11_06,
                                PRIMARY_2013_05_07,
                                PRIMARY_2013_09_10,
                                PRIMARY_2013_10_01,
                                GENERAL_2013_11_05,
                                PRIMARY_2014_05_06,
                                GENERAL_2014_11_04,
                                PRIMARY_2015_05_05,
                                PRIMARY_2015_09_15,
                                GENERAL_2015_11_03,
                                PRIMARY_2016_03_15,
                                GENERAL_2016_06_07,
                                PRIMARY_2016_09_13,
                                GENERAL_2016_11_08,
                                PRIMARY_2017_05_02,
                                PRIMARY_2017_09_12,
                                GENERAL_2017_11_07,
                                PRIMARY_2018_05_08,
                                GENERAL_2018_08_07,
                                GENERAL_2018_11_06,
                                PRIMARY_2019_05_07,
                                PRIMARY_2019_09_10,
                                GENERAL_2019_11_05,
                                PRIMARY_2020_03_17,
                                GENERAL_2020_11_03,
                                PRIMARY_2021_05_04,
                                PRIMARY_2021_08_03,
                                PRIMARY_2021_09_14,
                                GENERAL_2021_11_02,
                                PRIMARY_2022_05_03,
                                PRIMARY_2022_08_02,
                                GENERAL_2022_11_08,
                                SPECIAL_2023_02_28,
                                PRIMARY_2023_05_02,
                                SPECIAL_2023_08_08
                                )))
SELECT 'OH'                                                        AS STATE_CODE,
       COUNTY.county_name                                          AS COUNTY_CODE,
       SOS_VOTERID                                                 AS VOTER_ID,
       ELECTION_CODE,
       SUBSTR(ELECTION_CODE, 0, CHARINDEX('_', ELECTION_CODE) - 1) AS ELECTION_TYPE,
       TO_DATE(
               REPLACE(
                       SUBSTR(ELECTION_CODE, CHARINDEX('_', ELECTION_CODE) + 1),
                       '_',
                       '-'),
               'YYYY-MM-DD')                                       AS ELECTION_DATE,
       CASE
           WHEN VOTE_TYPE_CODE = 'C' THEN 'Constitution Party'
           WHEN VOTE_TYPE_CODE = 'D' THEN 'Democrat Party'
           WHEN VOTE_TYPE_CODE = 'E' THEN 'Reform Party'
           WHEN VOTE_TYPE_CODE = 'G' THEN 'Green Party'
           WHEN VOTE_TYPE_CODE = 'L' THEN 'Libertarian Party'
           WHEN VOTE_TYPE_CODE = 'N' THEN 'Natural Law Party'
           WHEN VOTE_TYPE_CODE = 'R' THEN 'Republican Party'
           WHEN VOTE_TYPE_CODE = 'S' THEN 'Socialist Party'
           WHEN VOTE_TYPE_CODE = 'X' THEN 'Unaffiliated' END       AS PARTY_VOTED,
       NULL                                                        AS DATE_OF_VOTING,
       TRUE                                                        AS WAS_VOTE_COUNTED,
       NULL::object                                                AS ADDITIONAL_DATA,
       'UNKNOWN'                                                   AS VOTING_METHOD
FROM OHIO_VOTER_HISTORY
         INNER JOIN __dbt__cte__ohio_counties COUNTY ON COUNTY_NUMBER = COUNTY.county_id