{{
    config(
        materialized='view'
    )
}}

SELECT STATE_CODE,
       SUM(COUNT) AS VOTER_COUNT,
       SUM(DID_MOVE) AS MOVED_COUNT,
       SUM(DID_MOVE_TO_ANOTHER_COUNTY) AS MOVED_TO_ANOTHER_COUNTY_COUNT,
       SUM(DID_MOVE_TO_ANOTHER_STATE) AS MOVED_TO_ANOTHER_STATE_COUNT,
       SUM(DID_VOTE_AFTER_MOVING) AS VOTED_AFTER_MOVING_COUNT
FROM NORMALIZED.FACT_VOTERS
GROUP BY STATE_CODE