



SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.georgia_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.michigan_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.florida_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.iowa_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.maryland_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.nevada_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.new_hampshire_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.pennsylvania_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.new_jersey_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.mississippi_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.alabama_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.arkansas_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.delaware_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.kansas_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.nebraska_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.montana_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.ohio_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.idaho_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.rhode_island_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.washington_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.west_virginia_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.wisconsin_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.vermont_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.utah_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.missouri_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.oklahoma_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.tennessee_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.district_of_columbia_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.connecticut_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1

UNION


SELECT STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       ELECTION_TYPE,
       ELECTION_DATE,
       PARTY_VOTED,
       VOTING_METHOD,
       DATE_OF_VOTING,
       WAS_VOTE_COUNTED,
       ADDITIONAL_DATA,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.california_voter_history T1
WHERE NOT EXISTS (SELECT 1
                  FROM DBT_VOTER_DATA.cleaned.all_voter_history T2
                  WHERE T1.STATE_CODE = T2.STATE_CODE
                    AND T1.ELECTION_DATE = T2.ELECTION_DATE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY STATE_CODE, COUNTY_CODE, VOTER_ID, ELECTION_DATE ORDER BY ELECTION_DATE) = 1
