



SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.georgia_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.kansas_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.michigan_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.arkansas_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.colorado_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.florida_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.iowa_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.maryland_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.nevada_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.new_hampshire_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.pennsylvania_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.wisconsin_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.ohio_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.north_carolina_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.south_carolina_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.oregon_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.montana_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.texas_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.new_jersey_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.idaho_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.mississippi_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.new_mexico_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.washington_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.louisiana_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.wyoming_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.west_virginia_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.alabama_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.colorado_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.delaware_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.nebraska_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.rhode_island_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.vermont_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.utah_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.missouri_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.oklahoma_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.tennessee_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.virginia_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.district_of_columbia_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.connecticut_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.new_york_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.california_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.arizona_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)



UNION


SELECT BASE64_ENCODE(
               UPPER(
                       ARRAY_TO_STRING(
                               ARRAY_CONSTRUCT_COMPACT(
                                       FILE_DATE, STATE_CODE, COUNTY_CODE, VOTER_ID), ' '))
       ) AS SK_VOTER_INFO_ID,
       FILE_DATE,
       STATE_CODE,
       COUNTY_CODE,
       VOTER_ID,
       PREFIX,
       FIRST_NAME,
       MIDDLE_NAME,
       LAST_NAME,
       NAME_SUFFIX,
       RESIDENCE_ADDRESS_LINE_1,
       RESIDENCE_ADDRESS_LINE_2,
       RESIDENCE_ADDRESS_CITY,
       RESIDENCE_ADDRESS_STATE,
       RESIDENCE_ADDRESS_ZIPCODE,
       RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR,
       BIRTH_MONTH,
       BIRTH_DATE,
       VOTER_STATUS,
       REGISTRATION_DATE,
       CONGRESSIONAL_DISTRICT,
       STATE_SENATE_DISTRICT,
       STATE_HOUSE_DISTRICT,
       JUDICIAL_DISTRICT,
       COUNTY_COMMISSION_DISTRICT,
       SCHOOL_BOARD_DISTRICT,
       CITY_COUNCIL_DISTRICT,
       COUNTY_PRECINCT,
       MUNICIPAL_PRECINCT,
       RACE,
       GENDER,
       MAILING_ADDRESS_LINE_1,
       MAILING_ADDRESS_LINE_2,
       MAILING_LINE_3,
       MAILING_CITY,
       MAILING_STATE,
       MAILING_ZIPCODE,
       MAILING_COUNTRY,
       LAST_VOTED_DATE,
       LAST_PARTY_VOTED,
       CURRENT_TIMESTAMP AS CREATED_AT
FROM DBT_VOTER_DATA.cleaned.south_dakota_voters T1
    
WHERE NOT EXISTS (SELECT 1 FROM DBT_VOTER_DATA.cleaned.all_voters T2 WHERE T1.FILE_DATE = T2.FILE_DATE AND T1.STATE_CODE = T2.STATE_CODE)


