with __dbt__cte__tennessee_counties as (


SELECT *
FROM (VALUES ('01', 'ANDERSON', '1'),
             ('02', 'BEDFORD', '2'),
             ('08', 'CANNON', '8'),
             ('03', 'BENTON', '3'),
             ('04', 'BLEDSOE', '4'),
             ('06', 'BRADLEY', '6'),
             ('05', 'BLOUNT', '5'),
             ('07', 'CAMPBELL', '7'),
             ('09', 'CARROLL', '9'),
             ('10', 'CARTER', '10'),
             ('11', 'CHEATHAM', '11'),
             ('12', 'CHESTER', '12'),
             ('13', 'CLAIBORNE', '13'),
             ('14', 'CLAY', '14'),
             ('15', 'COCKE', '15'),
             ('16', 'COFFEE', '16'),
             ('17', 'CROCKETT', '17'),
             ('19', 'DAVIDSON', '19'),
             ('18', 'CUMBERLAND', '18'),
             ('20', 'DECATUR', '20'),
             ('21', 'DEKALB', '21'),
             ('22', 'DICKSON', '22'),
             ('23', 'DYER', '23'),
             ('24', 'FAYETTE', '24'),
             ('25', 'FENTRESS', '25'),
             ('26', 'FRANKLIN', '26'),
             ('27', 'GIBSON', '27'),
             ('28', 'GILES', '28'),
             ('37', 'HAWKINS', '37'),
             ('36', 'HARDIN', '36'),
             ('29', 'GRAINGER', '29'),
             ('35', 'HARDEMAN', '35'),
             ('38', 'HAYWOOD', '38'),
             ('34', 'HANCOCK', '34'),
             ('33', 'HAMILTON', '33'),
             ('32', 'HAMBLEN', '32'),
             ('31', 'GRUNDY', '31'),
             ('30', 'GREENE', '30'),
             ('42', 'HOUSTON', '42'),
             ('43', 'HUMPHREYS', '43'),
             ('39', 'HENDERSON', '39'),
             ('40', 'HENRY', '40'),
             ('44', 'JACKSON', '44'),
             ('41', 'HICKMAN', '41'),
             ('45', 'JEFFERSON', '45'),
             ('46', 'JOHNSON', '46'),
             ('47', 'KNOX', '47'),
             ('53', 'LOUDON', '53'),
             ('52', 'LINCOLN', '52'),
             ('51', 'LEWIS', '51'),
             ('48', 'LAKE', '48'),
             ('50', 'LAWRENCE', '50'),
             ('54', 'MCMINN', '54'),
             ('49', 'LAUDERDALE', '49'),
             ('70', 'POLK', '70'),
             ('69', 'PICKETT', '69'),
             ('68', 'PERRY', '68'),
             ('67', 'OVERTON', '67'),
             ('66', 'OBION', '66'),
             ('64', 'MOORE', '64'),
             ('63', 'MONTGOMERY', '63'),
             ('71', 'PUTNAM', '71'),
             ('56', 'MACON', '56'),
             ('62', 'MONROE', '62'),
             ('61', 'MEIGS', '61'),
             ('55', 'MCNAIRY', '55'),
             ('60', 'MAURY', '60'),
             ('65', 'MORGAN', '65'),
             ('59', 'MARSHALL', '59'),
             ('58', 'MARION', '58'),
             ('57', 'MADISON', '57'),
             ('72', 'RHEA', '72'),
             ('74', 'ROBERTSON', '74'),
             ('75', 'RUTHERFORD', '75'),
             ('73', 'ROANE', '73'),
             ('76', 'SCOTT', '76'),
             ('77', 'SEQUATCHIE', '77'),
             ('88', 'VAN BUREN', '88'),
             ('89', 'WARREN', '89'),
             ('87', 'UNION', '87'),
             ('86', 'UNICOI', '86'),
             ('85', 'TROUSDALE', '85'),
             ('84', 'TIPTON', '84'),
             ('78', 'SEVIER', '78'),
             ('83', 'SUMNER', '83'),
             ('82', 'SULLIVAN', '82'),
             ('81', 'STEWART', '81'),
             ('79', 'SHELBY', '79'),
             ('80', 'SMITH', '80'),
             ('90', 'WASHINGTON', '90'),
             ('94', 'WILLIAMSON', '94'),
             ('93', 'WHITE', '93'),
             ('95', 'WILSON', '95'),
             ('91', 'WAYNE', '91'),
             ('92', 'WEAKLEY', '92')) AS A (COUNTY_ID, COUNTY_NAME, COUNTY_ID_INT)
) SELECT '2024-01-01'::date                       as FILE_DATE,
       'TN'                                     as STATE_CODE,
       C.COUNTY_NAME                            as COUNTY_CODE,
       VOTER_ID                                 AS VOTER_ID,
       NULL                                     AS PREFIX,
       FIRST_NAME                               AS FIRST_NAME,
       MIDDLE_NAME                              AS MIDDLE_NAME,
       LAST_NAME                                AS LAST_NAME,
       NAME_SUFFIX                              AS NAME_SUFFIX,
       RES_ADDRESS1                             AS RESIDENCE_ADDRESS_LINE_1,
       RES_ADDRESS2                             AS RESIDENCE_ADDRESS_LINE_2,
       RES_CITY                                 AS RESIDENCE_ADDRESS_CITY,
       COALESCE(RES_STATE, 'TN')                AS RESIDENCE_ADDRESS_STATE,
       RES_ZIP1                                 AS RESIDENCE_ADDRESS_ZIPCODE,
       'USA'                                    AS RESIDENCE_ADDRESS_COUNTRY,
       BIRTH_YEAR::number                       AS BIRTH_YEAR,
       BIRTH_MONTH::number                      AS BIRTH_MONTH,
       BIRTH_DAY::number                       AS BIRTH_DATE,
       STATUS                                   as VOTER_STATUS,
       TO_DATE(REGISTRATION_DATE, 'YYYY-MM-DD') AS REGISTRATION_DATE,
       NULL                                     AS LAST_VOTED_DATE,
       COALESCE(AUG_22_PARTY,
                AUG_20_PARTY,
                AUG_18_PARTY,
                AUG_16_PARTY,
                AUG_14_PARTY,
                AUG_12_PARTY,
                AUG_10_PARTY,
                AUG_08_PARTY,
                AUG_06_PARTY,
                AUG_04_PARTY,
                AUG_02_PARTY,
                AUG_00_PARTY)                   AS LAST_PARTY_VOTED,
       US_CONGRESS                              AS CONGRESSIONAL_DISTRICT,
       TN_SENATE                                AS STATE_SENATE_DISTRICT,
       TN_HOUSE                                 AS STATE_HOUSE_DISTRICT,
       JUDICIAL                                 AS JUDICIAL_DISTRICT,
       NULL                                     AS COUNTY_COMMISSION_DISTRICT,
       NULL                                     AS SCHOOL_BOARD_DISTRICT,
       NULL                                     AS CITY_COUNCIL_DISTRICT,
       PRECINCT                                 AS COUNTY_PRECINCT,
       NULL                                     AS MUNICIPAL_PRECINCT,
       CASE
           WHEN RACE = 'W' THEN 'White'
           WHEN RACE = 'B' THEN 'Black'
           WHEN RACE = 'O' THEN 'Other'
           ELSE 'Unknown'
           END                                  AS RACE,
       GENDER                                   AS GENDER,
       NULL                                     AS MAILING_ADDRESS_LINE_1,
       NULL                                     AS MAILING_ADDRESS_LINE_2,
       NULL                                     AS MAILING_LINE_3,
       NULL                                     AS MAILING_CITY,
       NULL                                     AS MAILING_STATE,
       NULL                                     AS MAILING_ZIPCODE,
       NULL                                     AS MAILING_COUNTRY
FROM DBT_VOTER_DATA.raw.TENNESSEE_VOTERS_2024_01_01 V
         INNER JOIN __dbt__cte__tennessee_counties C ON V.COUNTY = C.COUNTY_ID