

SELECT *
FROM (VALUES ('01', 'Albany'),
             ('02', 'Allegany'),
             ('03', 'Bronx'),
             ('04', 'Broome'),
             ('05', 'Cattaraugus'),
             ('06', 'Cayuga'),
             ('07', 'Chautauqua'),
             ('08', 'Chemung'),
             ('09', 'Chenango'),
             ('10', 'Clinton'),
             ('11', 'Columbia'),
             ('12', 'Cortland'),
             ('13', 'Delaware'),
             ('14', 'Dutchess'),
             ('15', 'Erie'),
             ('16', 'Essex'),
             ('17', 'Franklin'),
             ('18', 'Fulton'),
             ('19', 'Genesee'),
             ('20', 'Greene'),
             ('21', 'Hamilton'),
             ('22', 'Herkimer'),
             ('23', 'Jefferson'),
             ('24', 'Kings'),
             ('25', 'Lewis'),
             ('26', 'Livingston'),
             ('27', 'Madison'),
             ('28', 'Monroe'),
             ('29', 'Montgomery'),
             ('30', 'Nassau'),
             ('31', 'New York'),
             ('32', 'Niagara'),
             ('33', 'Oneida'),
             ('34', 'Onondaga'),
             ('35', 'Ontario'),
             ('36', 'Orange'),
             ('37', 'Orleans'),
             ('38', 'Oswego'),
             ('39', 'Otsego'),
             ('40', 'Putnam'),
             ('41', 'Queens'),
             ('42', 'Rensselaer'),
             ('43', 'Richmond'),
             ('44', 'Rockland'),
             ('45', 'Saratoga'),
             ('46', 'Schenectady'),
             ('47', 'Schoharie'),
             ('48', 'Schuyler'),
             ('49', 'Seneca'),
             ('50', 'St Lawrence'),
             ('51', 'Steuben'),
             ('52', 'Suffolk'),
             ('53', 'Sullivan'),
             ('54', 'Tioga'),
             ('55', 'Tompkins'),
             ('56', 'Ulster'),
             ('57', 'Warren'),
             ('58', 'Washington'),
             ('59', 'Wayne'),
             ('60', 'Westchester'),
             ('61', 'Wyoming'),
             ('62', 'Yates')) AS A (COUNTY_ID, COUNTY_NAME)