SELECT *
FROM (VALUES ('001', 'Andover', 'Tolland'),
             ('002', 'Ansonia', 'New Haven'),
             ('003', 'Ashford', 'Windham'),
             ('004', 'Avon', 'Hartford'),
             ('005', 'Barkhamsted', 'Litchfield'),
             ('006', 'Beacon Falls', 'New Haven'),
             ('007', 'Berlin', 'Hartford'),
             ('008', 'Bethany', 'New Haven'),
             ('009', 'Bethel', 'Fairfield'),
             ('010', 'Bethlehem', 'Litchfield'),
             ('011', 'Bloomfield', 'Hartford'),
             ('012', 'Bolton', 'Tolland'),
             ('013', 'Bozrah', 'New London'),
             ('014', 'Branford', 'New Haven'),
             ('015', 'Bridgeport', 'Fairfield'),
             ('016', 'Bridgewater', 'Litchfield'),
             ('017', 'Bristol', 'Hartford'),
             ('018', 'Brookfield', 'Fairfield'),
             ('019', 'Brooklyn', 'Windham'),
             ('020', 'Burlington', 'Hartford'),
             ('021', 'Canaan', 'Litchfield'),
             ('022', 'Canterbury', 'Windham'),
             ('023', 'Canton', 'Hartford'),
             ('024', 'Chaplin', 'Windham'),
             ('025', 'Cheshire', 'New Haven'),
             ('026', 'Chester', 'Middlesex'),
             ('027', 'Clinton', 'Middlesex'),
             ('028', 'Colchester', 'New London'),
             ('029', 'Colebrook', 'Litchfield'),
             ('030', 'Columbia', 'Tolland'),
             ('031', 'Cornwall', 'Litchfield'),
             ('032', 'Coventry', 'Tolland'),
             ('033', 'Cromwell', 'Middlesex'),
             ('034', 'Danbury', 'Fairfield'),
             ('035', 'Darien', 'Fairfield'),
             ('036', 'Deep River', 'Middlesex'),
             ('037', 'Derby', 'New Haven'),
             ('038', 'Durham', 'Middlesex'),
             ('039', 'East Granby', 'Hartford'),
             ('040', 'East Haddam', 'Middlesex'),
             ('041', 'East Hampton', 'Middlesex'),
             ('042', 'East Hartford', 'Hartford'),
             ('043', 'East Haven', 'New Haven'),
             ('044', 'East Lyme', 'New London'),
             ('045', 'East Windsor', 'Hartford'),
             ('046', 'Eastford', 'Windham'),
             ('047', 'Easton', 'Fairfield'),
             ('048', 'Ellington', 'Tolland'),
             ('049', 'Enfield', 'Hartford'),
             ('050', 'Essex', 'Middlesex'),
             ('051', 'Fairfield', 'Fairfield'),
             ('052', 'Farmington', 'Hartford'),
             ('053', 'Franklin', 'New London'),
             ('054', 'Glastonbury', 'Hartford'),
             ('055', 'Goshen', 'Litchfield'),
             ('056', 'Granby', 'Hartford'),
             ('057', 'Greenwich', 'Fairfield'),
             ('058', 'Griswold', 'New London'),
             ('059', 'Groton', 'New London'),
             ('060', 'Guilford', 'New Haven'),
             ('061', 'Haddam', 'Middlesex'),
             ('062', 'Hamden', 'New Haven'),
             ('063', 'Hampton', 'Windham'),
             ('064', 'Hartford', 'Hartford'),
             ('065', 'Hartland', 'Hartford'),
             ('066', 'Harwinton', 'Litchfield'),
             ('067', 'Hebron', 'Tolland'),
             ('068', 'Kent', 'Litchfield'),
             ('069', 'Killingly', 'Windham'),
             ('070', 'Killingworth', 'Middlesex'),
             ('071', 'Lebanon', 'New London'),
             ('072', 'Ledyard', 'New London'),
             ('073', 'Lisbon', 'New London'),
             ('074', 'Litchfield', 'Litchfield'),
             ('075', 'Lyme', 'New London'),
             ('076', 'Madison', 'New Haven'),
             ('077', 'Manchester', 'Hartford'),
             ('078', 'Mansfield', 'Tolland'),
             ('079', 'Marlborough', 'Hartford'),
             ('080', 'Meriden', 'New Haven'),
             ('081', 'Middlebury', 'New Haven'),
             ('082', 'Middlefield', 'Middlesex'),
             ('083', 'Middletown', 'Middlesex'),
             ('084', 'Milford', 'New Haven'),
             ('085', 'Monroe', 'Fairfield'),
             ('086', 'Montville', 'New London'),
             ('087', 'Morris', 'Litchfield'),
             ('088', 'Naugatuck', 'New Haven'),
             ('089', 'New Britain', 'Hartford'),
             ('090', 'New Canaan', 'Fairfield'),
             ('091', 'New Fairfield', 'Fairfield'),
             ('092', 'New Hartford', 'Litchfield'),
             ('093', 'New Haven', 'New Haven'),
             ('094', 'New London', 'New London'),
             ('095', 'New Milford', 'Litchfield'),
             ('096', 'Newington', 'Hartford'),
             ('097', 'Newtown', 'Fairfield'),
             ('098', 'Norfolk', 'Litchfield'),
             ('099', 'North Branford', 'New Haven'),
             ('100', 'North Canaan', 'Litchfield'),
             ('101', 'North Haven', 'New Haven'),
             ('102', 'North Stonington', 'New London'),
             ('103', 'Norwalk', 'Fairfield'),
             ('104', 'Norwich', 'New London'),
             ('105', 'Old Lyme', 'New London'),
             ('106', 'Old Saybrook', 'Middlesex'),
             ('107', 'Orange', 'New Haven'),
             ('108', 'Oxford', 'New Haven'),
             ('109', 'Plainfield', 'Windham'),
             ('110', 'Plainville', 'Hartford'),
             ('111', 'Plymouth', 'Litchfield'),
             ('112', 'Pomfret', 'Windham'),
             ('113', 'Portland', 'Middlesex'),
             ('114', 'Preston', 'New London'),
             ('115', 'Prospect', 'New Haven'),
             ('116', 'Putnam', 'Windham'),
             ('117', 'Redding', 'Fairfield'),
             ('118', 'Ridgefield', 'Fairfield'),
             ('119', 'Rocky Hill', 'Hartford'),
             ('120', 'Roxbury', 'Litchfield'),
             ('121', 'Salem', 'New London'),
             ('122', 'Salisbury', 'Litchfield'),
             ('123', 'Scotland', 'Windham'),
             ('124', 'Seymour', 'New Haven'),
             ('125', 'Sharon', 'Litchfield'),
             ('126', 'Shelton', 'Fairfield'),
             ('127', 'Sherman', 'Fairfield'),
             ('128', 'Simsbury', 'Hartford'),
             ('129', 'Somers', 'Tolland'),
             ('130', 'South Windsor', 'Hartford'),
             ('131', 'Southbury', 'New Haven'),
             ('132', 'Southington', 'Hartford'),
             ('133', 'Sprague', 'New London'),
             ('134', 'Stafford', 'Tolland'),
             ('135', 'Stamford', 'Fairfield'),
             ('136', 'Sterling', 'Windham'),
             ('137', 'Stonington', 'New London'),
             ('138', 'Stratford', 'Fairfield'),
             ('139', 'Suffield', 'Hartford'),
             ('140', 'Thomaston', 'Litchfield'),
             ('141', 'Thompson', 'Windham'),
             ('142', 'Tolland', 'Tolland'),
             ('143', 'Torrington', 'Litchfield'),
             ('144', 'Trumbull', 'Fairfield'),
             ('145', 'Union', 'Tolland'),
             ('146', 'Vernon', 'Tolland'),
             ('147', 'Voluntown', 'New London'),
             ('148', 'Wallingford', 'New Haven'),
             ('149', 'Warren', 'Litchfield'),
             ('150', 'Washington', 'Litchfield'),
             ('151', 'Waterbury', 'New Haven'),
             ('152', 'Waterford', 'New London'),
             ('153', 'Watertown', 'Litchfield'),
             ('154', 'West Hartford', 'Hartford'),
             ('155', 'West Haven', 'New Haven'),
             ('156', 'Westbrook', 'Middlesex'),
             ('157', 'Weston', 'Fairfield'),
             ('158', 'Westport', 'Fairfield'),
             ('159', 'Wethersfield', 'Hartford'),
             ('160', 'Willington', 'Tolland'),
             ('161', 'Wilton', 'Fairfield'),
             ('162', 'Winchester', 'Litchfield'),
             ('163', 'Windham', 'Windham'),
             ('164', 'Windsor', 'Hartford'),
             ('165', 'Windsor Locks', 'Hartford'),
             ('166', 'Wolcott', 'New Haven'),
             ('167', 'Woodbridge', 'New Haven'),
             ('168', 'Woodbury', 'Litchfield'),
             ('169', 'Woodstock', 'Windham')
         ) AS A (TOWN_ID, TOWN_NAME,COUNTY_NAME)