
SELECT *
FROM (VALUES ('01', 'Beaverhead'),
             ('11', 'Dawson'),
             ('21', 'Hill'),
             ('31', 'Mineral'),
             ('41', 'Ravalli'),
             ('51', 'Toole'),
             ('02', 'Big Horn'),
             ('12', 'Deer Lodge'),
             ('22', 'Jefferson'),
             ('32', 'Missoula'),
             ('42', 'Richland'),
             ('52', 'Treasure'),
             ('03', 'Blaine'),
             ('13', 'Fallon'),
             ('23', 'Judith Basin'),
             ('33', 'Musselshell'),
             ('43', 'Roosevelt'),
             ('53', 'Valley'),
             ('04', 'Broadwater'),
             ('14', 'Fergus'),
             ('24', 'Lake'),
             ('34', 'Park'),
             ('44', 'Rosebud'),
             ('54', 'Wheatland'),
             ('05', 'Carbon'),
             ('15', 'Flathead'),
             ('25', 'Lewis and Clark'),
             ('35', 'Petroleum'),
             ('45', 'Sanders'),
             ('55', 'Wibaux'),
             ('06', 'Carter'),
             ('16', 'Gallatin'),
             ('26', 'Liberty'),
             ('36', 'Phillips'),
             ('46', 'Sheridan'),
             ('56', 'Yellowstone'),
             ('07', 'Cascade'),
             ('17', 'Garfield'),
             ('27', 'Lincoln'),
             ('37', 'Pondera'),
             ('47', 'Silver Bow'),
             ('08', 'Chouteau'),
             ('18', 'Glacier'),
             ('28', 'Madison'),
             ('38', 'Powder River'),
             ('48', 'Stillwater'),
             ('09', 'Custer'),
             ('19', 'Golden Valley'),
             ('29', 'McCone'),
             ('39', 'Powell'),
             ('49', 'Sweet Grass'),
             ('10', 'Daniels'),
             ('20', 'Granite'),
             ('30', 'Meagher'),
             ('40', 'Prairie'),
             ('50', 'Teton')) AS A (COUNTY_ID, COUNTY_NAME)