{% macro import_arkansas_voters() %}

CREATE TABLE IF NOT EXISTS RAW.arkansas_voters_2023_09_01
(
    county                         TEXT,
    key_registrant                 TEXT,
    voter_id                       TEXT,
    cde_registrant_status          TEXT,
    cde_registrant_reason          TEXT,
    date_of_birth                  TEXT,
    date_of_registration           TEXT,
    cde_name_title                 TEXT,
    text_name_last                 TEXT,
    text_name_first                TEXT,
    text_name_middle               TEXT,
    cde_name_suffix                TEXT,
    text_res_address_nbr           TEXT,
    text_res_address_nbr_suffix    TEXT,
    cde_street_dir_prefix          TEXT,
    text_street_name               TEXT,
    desc_street_type               TEXT,
    cde_street_dir_suffix          TEXT,
    desc_unit_type                 TEXT,
    text_res_unit_nbr              TEXT,
    text_res_city                  TEXT,
    cde_res_state                  TEXT,
    text_res_zip5                  TEXT,
    text_res_zip4                  TEXT,
    ind_mail                       TEXT,
    text_mail_address1             TEXT,
    text_mail_address2             TEXT,
    text_mail_address3             TEXT,
    text_mail_address4             TEXT,
    text_mail_city                 TEXT,
    cde_mail_state                 TEXT,
    text_mail_zip5                 TEXT,
    text_mail_zip4                 TEXT,
    precinct_name                  TEXT,
    precinct_designation_code      TEXT,
    precinct_part_name             TEXT,
    precinct_part_designation_code TEXT,
    cde_party                      TEXT,
    date_of_party_affiliation      TEXT,
    text_phone_area_code           TEXT,
    text_phone_exchange            TEXT,
    text_phone_last_four           TEXT,
    text_res_physical_address      TEXT,
    water_board_district           TEXT,
    congressional_district         TEXT,
    state_senate_district          TEXT,
    state_representative_district  TEXT,
    court_of_appeals_district      TEXT,
    judicial_district              TEXT,
    judicial_district_subdivision  TEXT,
    district_court_district        TEXT,
    township_district              TEXT,
    justice_of_the_peace_district  TEXT,
    school_district                TEXT,
    school_district_zone           TEXT,
    municipality_district          TEXT,
    ward_district                  TEXT,
    levee_district                 TEXT,
    suburban_improvement_district  TEXT,
    subordinate_services_district  TEXT,
    solid_waste_district           TEXT,
    technical_school_district      TEXT,
    volunteer_fire_district        TEXT,
    date_last_voted                TEXT
);

CREATE TABLE IF NOT EXISTS RAW.arkansas_ncoa_results_2023_09_01
(
    input_id                            TEXT,
    input_firstname                     TEXT,
    input_middlename                    TEXT,
    input_lastname                      TEXT,
    input_suffix                        TEXT,
    input_addressline1                  TEXT,
    input_addressline2                  TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zipcode                       TEXT,
    input_county                        TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

CREATE TABLE IF NOT EXISTS RAW.arkansas_voter_history_2023_09_01
(
    county                                               TEXT,
    voterid                                              TEXT,
    key_registrant                                       TEXT,
    cde_registrant_status                                TEXT,
    cde_registrant_reason                                TEXT,
    date_of_birth                                        TEXT,
    date_of_registration                                 TEXT,
    cde_name_title                                       TEXT,
    text_name_last                                       TEXT,
    text_name_first                                      TEXT,
    text_name_middle                                     TEXT,
    cde_name_suffix                                      TEXT,
    text_res_address_nbr                                 TEXT,
    text_res_address_nbr_suffix                          TEXT,
    cde_street_dir_prefix                                TEXT,
    text_street_name                                     TEXT,
    desc_street_type                                     TEXT,
    cde_street_dir_suffix                                TEXT,
    desc_unit_type                                       TEXT,
    text_res_unit_nbr                                    TEXT,
    text_res_city                                        TEXT,
    cde_res_state                                        TEXT,
    text_res_zip5                                        TEXT,
    text_res_zip4                                        TEXT,
    ind_mail                                             TEXT,
    text_mail_address1                                   TEXT,
    text_mail_address2                                   TEXT,
    text_mail_address3                                   TEXT,
    text_mail_address4                                   TEXT,
    text_mail_city                                       TEXT,
    cde_mail_state                                       TEXT,
    text_mail_zip5                                       TEXT,
    text_mail_zip4                                       TEXT,
    precinct_name                                        TEXT,
    precinct_designation_code                            TEXT,
    precinct_part_name                                   TEXT,
    precinct_part_designation_code                       TEXT,
    cde_party                                            TEXT,
    date_of_party_affiliation                            TEXT,
    text_phone_area_code                                 TEXT,
    text_phone_exchange                                  TEXT,
    text_phone_last_four                                 TEXT,
    text_res_physical_address                            TEXT,
    water_board_district                                 TEXT,
    congressional_district                               TEXT,
    state_senate_district                                TEXT,
    state_representative_district                        TEXT,
    court_of_appeals_district                            TEXT,
    judicial_district                                    TEXT,
    judicial_district_subdivision                        TEXT,
    district_court_district                              TEXT,
    township_district                                    TEXT,
    justice_of_the_peace_district                        TEXT,
    school_district                                      TEXT,
    school_district_zone                                 TEXT,
    municipality_district                                TEXT,
    ward_district                                        TEXT,
    levee_district                                       TEXT,
    suburban_improvement_district                        TEXT,
    subordinate_services_district                        TEXT,
    solid_waste_district                                 TEXT,
    technical_school_district                            TEXT,
    volunteer_fire_district                              TEXT,
    date_last_voted                                      TEXT,
    general_lg24_2011                                    TEXT,
    general_lg24_2011_county_voted_in                    TEXT,
    general_lg24_2011_party_voted                        TEXT,
    general_lg24_2011_how_voted                          TEXT,
    primary_lg54_2011                                    TEXT,
    primary_lg54_2011_county_voted_in                    TEXT,
    primary_lg54_2011_party_voted                        TEXT,
    primary_lg54_2011_how_voted                          TEXT,
    primary_runoff_lg54_2011                             TEXT,
    primary_runoff_lg54_2011_county_voted_in             TEXT,
    primary_runoff_lg54_2011_party_voted                 TEXT,
    primary_runoff_lg54_2011_how_voted                   TEXT,
    general_lg54_2011                                    TEXT,
    general_lg54_2011_county_voted_in                    TEXT,
    general_lg54_2011_party_voted                        TEXT,
    general_lg54_2011_how_voted                          TEXT,
    hwybonds_2011                                        TEXT,
    hwybonds_2011_county_voted_in                        TEXT,
    hwybonds_2011_party_voted                            TEXT,
    hwybonds_2011_how_voted                              TEXT,
    primary2012                                          TEXT,
    primary_2012_county_voted_in                         TEXT,
    primary_2012_party_voted                             TEXT,
    primary_2012how_voted                                TEXT,
    primary_runoff_2012                                  TEXT,
    primary_runoff_2012_county_voted_in                  TEXT,
    primary_runoff_2012_party_voted                      TEXT,
    primary_runoff_2012_how_voted                        TEXT,
    general_2012                                         TEXT,
    general_2012_county_voted_in                         TEXT,
    general_2012_party_voted                             TEXT,
    general_2012_how_voted                               TEXT,
    primary_sd21_2014                                    TEXT,
    primary_sd21_2014_county_voted_in                    TEXT,
    primary_sd21_2014_party_voted                        TEXT,
    primary_sd21_2014_how_voted                          TEXT,
    primary_runoffs_d21_2014                             TEXT,
    primary_runoffs_d21_2014_county_voted_in             TEXT,
    primary_runoffs_d21_2014_party_voted                 TEXT,
    primary_runoffs_d21_2014_how_voted                   TEXT,
    general_sd21_2014                                    TEXT,
    general_sd21_2014_county_voted_in                    TEXT,
    general_sd21_2014_party_voted                        TEXT,
    general_sd21_2014_how_voted                          TEXT,
    primary_2014                                         TEXT,
    primary_2014_county_voted_in                         TEXT,
    primary_2014_party_voted                             TEXT,
    primary_2014_how_voted                               TEXT,
    primary_runoff_2014                                  TEXT,
    primary_runoff_2014_county_voted_in                  TEXT,
    primary_runoff_2014_party_voted                      TEXT,
    primary_runoff_2014_how_voted                        TEXT,
    general_2014                                         TEXT,
    general_2014_county_voted_in                         TEXT,
    general_2014_party_voted                             TEXT,
    general_2014_how_voted                               TEXT,
    primary_spsn16                                       TEXT,
    primary_spsn16_county_voted_in                       TEXT,
    primary_spsn16_party_voted                           TEXT,
    primary_spsn16_how_voted                             TEXT,
    primary_runoff_spsn16                                TEXT,
    primary_runoff_spsn16_county_voted_in                TEXT,
    primary_runoff_spsn16_party_voted                    TEXT,
    primary_runoff_spsn16_how_voted                      TEXT,
    general_spsn_16                                      TEXT,
    general_spsn_16_county_voted_in                      TEXT,
    general_spsn_16_party_voted                          TEXT,
    general_spsn_16_how_voted                            TEXT,
    primary_2016                                         TEXT,
    primary_2016_county_voted_in                         TEXT,
    primary_2016_party_voted                             TEXT,
    primary_2016_how_voted                               TEXT,
    primary_runoff_2016                                  TEXT,
    primary_runoff_2016_county_voted_in                  TEXT,
    primary_runoff_2016_party_voted                      TEXT,
    primary_runoff_2016_how_voted                        TEXT,
    general_2016                                         TEXT,
    general_2016_county_voted_in                         TEXT,
    general_2016_party_voted                             TEXT,
    general_2016_how_voted                               TEXT,
    special_primary_2018_election                        TEXT,
    special_primary_election_county_2018_voted_in        TEXT,
    special_primary_election_2018_party_voted            TEXT,
    special_primary_election_2018_how_voted              TEXT,
    special_primary_runoff_2018_election                 TEXT,
    special_primary_runoff_election_county_2018_voted_in TEXT,
    special_primary_runoff_election_2018_party_voted     TEXT,
    special_primary_runoff_election_2018_how_voted       TEXT,
    preferential_primary_2018                            TEXT,
    preferential_primary_2018_county_voted_in            TEXT,
    preferential_primary_2018_party_voted                TEXT,
    preferential_primary_2018_how_voted                  TEXT,
    primary_runoff_2018                                  TEXT,
    primary_runoff_2018_county_voted_in                  TEXT,
    primary_runoff_2018_party_voted                      TEXT,
    primary_runoff_2018_how_voted                        TEXT,
    general_2018                                         TEXT,
    general_county_2018_voted_in                         TEXT,
    general_2018_party_voted                             TEXT,
    general_runoff_2018                                  TEXT,
    general_runoff_county_2018_voted_in                  TEXT,
    general_runoff_2018_party_voted                      TEXT,
    general_2018_how_voted                               TEXT,
    general_runoff_2018_how_voted                        TEXT,
    preferential_primary_2020                            TEXT,
    preferential_primary_2020_voted_in                   TEXT,
    preferential_primary_2020_party_voted                TEXT,
    preferential_primary_2020_how_voted                  TEXT,
    primary_runoff_2020                                  TEXT,
    primary_runoff_2020_voted_in                         TEXT,
    primary_runoff_2020_party_voted                      TEXT,
    primary_runoff_2020_how_voted                        TEXT,
    general_2020                                         TEXT,
    general_2020_county_voted_in_2020                    TEXT,
    general_2020_party_voted                             TEXT,
    general_2020_how_voted                               TEXT,
    primary_2022                                         TEXT,
    primary_county_2022_voted_in                         TEXT,
    primary_2022_party_voted                             TEXT,
    primary_2022_how_voted                               TEXT,
    primary_runoff_2022                                  TEXT,
    primary_runoff_county_2022_voted_in                  TEXT,
    primary_runoff_2022_party_voted                      TEXT,
    primary_runoff_2022_how_voted                        TEXT,
    general_2022                                         TEXT,
    general_county_2022_voted_in                         TEXT,
    general_2022_party_voted                             TEXT,
    general_2022_how_voted                               TEXT,
    general_runoff_2022                                  TEXT,
    general_runoff_county_2022_voted_in                  TEXT,
    general_runoff_2022_party_voted                      TEXT,
    general_runoff_2022_how_voted                        TEXT
);

COPY INTO RAW.arkansas_voters_2023_09_01
    FROM @VOTER_FILES/arkansas/raw_data/file_date=2023_09_01/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        REPLACE_INVALID_CHARACTERS = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '')
        )
    ON_ERROR = 'CONTINUE';

COPY INTO RAW.arkansas_ncoa_results_2023_09_01
    FROM @VOTER_FILES/arkansas/ncoa_results/file_date=2023_09_01/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT';


COPY INTO RAW.arkansas_voter_history_2023_09_01
    FROM @VOTER_FILES/arkansas/voter_history/file_date=2023_09_01/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        REPLACE_INVALID_CHARACTERS = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '')
        )
    ON_ERROR = 'CONTINUE'

{% endmacro %}