{% macro import_iowa_voters() %}

create table if not exists RAW.iowa_voters_2023_12_14
(
    REGN_NUM                           VARCHAR,
    FIRST_NAME                         VARCHAR,
    MIDDLE_NAME                        VARCHAR,
    LAST_NAME                          VARCHAR,
    NAME_SUFFIX                        VARCHAR,
    EFF_REGN_DATE                      VARCHAR,
    LAST_UPDATED_DATE                  VARCHAR,
    OLD_ID                             VARCHAR,
    PHONE_NO                           VARCHAR,
    HOUSE_NUM                          VARCHAR,
    HOUSE_SUFFIX                       VARCHAR,
    PRE_DIR                            VARCHAR,
    STREET_NAME                        VARCHAR,
    STREET_TYPE                        VARCHAR,
    POST_DIR                           VARCHAR,
    UNIT_TYPE                          VARCHAR,
    UNIT_NUM                           VARCHAR,
    ADDRESS_NON_STD                    VARCHAR,
    CITY                               VARCHAR,
    STATE                              VARCHAR,
    ZIP_CODE                           VARCHAR,
    ZIP_PLUS                           VARCHAR,
    MAILING_ADDRESS                    VARCHAR,
    MAILING_ADDRESS_CITY               VARCHAR,
    MAILING_ADDRESS_STATE              VARCHAR,
    MAILING_ADDRESS_ZIP_CODE           VARCHAR,
    MAILING_ADDRESS_ZIP_PLUS           VARCHAR,
    VOTERSTATUS                        VARCHAR,
    PARTY                              VARCHAR,
    POLITICAL_ORGANIZATION             VARCHAR,
    GENDER                             VARCHAR,
    BIRTHDATE                          VARCHAR,
    COUNTY                             VARCHAR,
    FEDERAL                            VARCHAR,
    CONGRESSIONAL                      VARCHAR,
    STATEWIDE                          VARCHAR,
    STATE_SENATE                       VARCHAR,
    STATE_HOUSE                        VARCHAR,
    JUDICIAL                           VARCHAR,
    PRECINCT                           VARCHAR,
    COUNTY_SUPERVISOR                  VARCHAR,
    COUNTYWIDE                         VARCHAR,
    TOWNSHIP                           VARCHAR,
    CITY_COUNCIL_WARD                  VARCHAR,
    CITY_2                             VARCHAR,
    COMMUNITY_COLLEGE_DIRECTOR         VARCHAR,
    COMMUNITY_COLLEGE                  VARCHAR,
    SCHOOL_DIRECTOR                    VARCHAR,
    SCHOOL                             VARCHAR,
    SANITARY                           VARCHAR,
    AGRICULTURAL_EXTENSION             VARCHAR,
    SOIL_AND_WATER                     VARCHAR,
    WATER                              VARCHAR,
    FIRE                               VARCHAR,
    LAND                               VARCHAR,
    LAKE                               VARCHAR,
    LOSST_CONTIGUOUS_CITIES            VARCHAR,
    RECREATIONAL                       VARCHAR,
    RURAL_IMPROVEMENT_ZONE             VARCHAR,
    SEWER                              VARCHAR,
    LIGHT                              VARCHAR,
    MISCELLANEOUS                      VARCHAR,
    GENERAL_ELECTION_DATE_1            VARCHAR,
    GENERAL_VOTER_VOTE_METHOD_1        VARCHAR,
    GENERAL_ELECTION_DATE_2            VARCHAR,
    GENERAL_VOTER_VOTE_METHOD_2        VARCHAR,
    GENERAL_ELECTION_DATE_3            VARCHAR,
    GENERAL_VOTER_VOTE_METHOD_3        VARCHAR,
    GENERAL_ELECTION_DATE_4            VARCHAR,
    GENERAL_VOTER_VOTE_METHOD_4        VARCHAR,
    GENERAL_ELECTION_DATE_5            VARCHAR,
    GENERAL_VOTER_VOTE_METHOD_5        VARCHAR,
    PRIMARY_ELECTION_DATE_1            VARCHAR,
    PRIMARY_VOTER_VOTE_METHOD_1        VARCHAR,
    POLITICAL_PARTY_1                  VARCHAR,
    POLITICAL_ORGANIZATION_1           VARCHAR,
    PRIMARY_ELECTION_DATE_2            VARCHAR,
    PRIMARY_VOTER_VOTE_METHOD_2        VARCHAR,
    POLITICAL_PARTY_2                  VARCHAR,
    POLITICAL_ORGANIZATION_2           VARCHAR,
    PRIMARY_ELECTION_DATE_3            VARCHAR,
    PRIMARY_VOTER_VOTE_METHOD_3        VARCHAR,
    POLITICAL_PARTY_3                  VARCHAR,
    POLITICAL_ORGANIZATION_3           VARCHAR,
    PRIMARY_ELECTION_DATE_4            VARCHAR,
    PRIMARY_VOTER_VOTE_METHOD_4        VARCHAR,
    POLITICAL_PARTY_4                  VARCHAR,
    POLITICAL_ORGANIZATION_4           VARCHAR,
    PRIMARY_ELECTION_DATE_5            VARCHAR,
    PRIMARY_VOTER_VOTE_METHOD_5        VARCHAR,
    POLITICAL_PARTY_5                  VARCHAR,
    POLITICAL_ORGANIZATION_5           VARCHAR,
    CITY_OR_SCHOOL_ELECTION_DATE_1     VARCHAR,
    CITY_OR_SCHOOL_VOTER_VOTE_METHOD_1 VARCHAR,
    CITY_OR_SCHOOL_ELECTION_DATE_2     VARCHAR,
    CITY_OR_SCHOOL_VOTER_VOTE_METHOD_2 VARCHAR,
    CITY_OR_SCHOOL_ELECTION_DATE_3     VARCHAR,
    CITY_OR_SCHOOL_VOTER_VOTE_METHOD_3 VARCHAR,
    CITY_OR_SCHOOL_ELECTION_DATE_4     VARCHAR,
    CITY_OR_SCHOOL_VOTER_VOTE_METHOD_4 VARCHAR,
    CITY_OR_SCHOOL_ELECTION_DATE_5     VARCHAR,
    CITY_OR_SCHOOL_VOTER_VOTE_METHOD_5 VARCHAR,
    SCHOOL_ELECTION_DATE_1             VARCHAR,
    SCHOOL_VOTER_VOTE_METHOD_1         VARCHAR,
    SCHOOL_ELECTION_DATE_2             VARCHAR,
    SCHOOL_VOTER_VOTE_METHOD_2         VARCHAR,
    SCHOOL_ELECTION_DATE_3             VARCHAR,
    SCHOOL_VOTER_VOTE_METHOD_3         VARCHAR,
    SCHOOL_ELECTION_DATE_4             VARCHAR,
    SCHOOL_VOTER_VOTE_METHOD_4         VARCHAR,
    SCHOOL_ELECTION_DATE_5             VARCHAR,
    SCHOOL_VOTER_VOTE_METHOD_5         VARCHAR,
    CITY_ELECTION_DATE_1               VARCHAR,
    CITY_VOTER_VOTE_METHOD_1           VARCHAR,
    CITY_ELECTION_DATE_2               VARCHAR,
    CITY_VOTER_VOTE_METHOD_3           VARCHAR,
    CITY_ELECTION_DATE_3               VARCHAR,
    CITY_VOTER_VOTE_METHOD_4           VARCHAR,
    CITY_ELECTION_DATE_4               VARCHAR,
    CITY_VOTER_VOTE_METHOD_5           VARCHAR,
    CITY_ELECTION_DATE_5               VARCHAR,
    CITY_VOTER_VOTE_METHOD_6           VARCHAR,
    SPECIAL_ELECTION_DATE_1            VARCHAR,
    SPECIAL_VOTER_VOTE_METHOD_1        VARCHAR,
    SPECIAL_ELECTION_DATE_2            VARCHAR,
    SPECIAL_VOTER_VOTE_METHOD_2        VARCHAR,
    SPECIAL_ELECTION_DATE_3            VARCHAR,
    SPECIAL_VOTER_VOTE_METHOD_3        VARCHAR,
    SPECIAL_ELECTION_DATE_4            VARCHAR,
    SPECIAL_VOTER_VOTE_METHOD_4        VARCHAR,
    SPECIAL_ELECTION_DATE_5            VARCHAR,
    SPECIAL_VOTER_VOTE_METHOD_5        VARCHAR,
    EMPTY_COL_1                        VARCHAR,
    EMPTY_COL_2                        VARCHAR,
    EMPTY_COL_3                        VARCHAR,
    EMPTY_COL_4                        VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.iowa_ncoa_data_2023_12_14
(
    input_id                            TEXT,
    input_first_name                    TEXT,
    input_middle_name                   TEXT,
    input_last_name                     TEXT,
    input_name_suffix                   TEXT,
    input_address_1                     TEXT,
    input_address_2                     TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zip_code                      TEXT,
    input_county                        TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

CREATE TABLE IF NOT EXISTS RAW.iowa_voter_history_2023_12_14
(
    county               TEXT,
    voter_id             TEXT,
    election_date        TEXT,
    election_description TEXT,
    vote_method          TEXT,
    party                TEXT
);

COPY INTO RAW.iowa_voters_2023_12_14
    FROM @VOTER_FILES/iowa/raw_data/file_date=2023_12_14/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', ''),
        ERROR_ON_COLUMN_COUNT_MISMATCH = false
        )
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.iowa_ncoa_data_2023_12_14
    FROM @VOTER_FILES/iowa/ncoa_data/file_date=2023_09_08/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', ''),
        ERROR_ON_COLUMN_COUNT_MISMATCH = false
        )
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.iowa_voter_history_2023_12_14
    FROM @VOTER_FILES/iowa/voter_history/file_date=2023_09_08/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', ''),
        ERROR_ON_COLUMN_COUNT_MISMATCH = false
        )
    ON_ERROR = 'ABORT_STATEMENT'

{% endmacro %}