{% macro import_kansas_voters() %}

CREATE TABLE IF NOT EXISTS RAW.kansas_voters_2023_11_06
(
    db_logid                    TEXT,
    cde_registrant_status       TEXT,
    cde_name_title              TEXT,
    text_name_first             TEXT,
    text_name_middle            TEXT,
    text_name_last              TEXT,
    cde_name_suffix             TEXT,
    cde_gender                  TEXT,
    text_registrant_id          TEXT,
    text_res_address_nbr        TEXT,
    text_res_address_nbr_suffix TEXT,
    cde_street_dir_prefix       TEXT,
    text_street_name            TEXT,
    cde_street_type             TEXT,
    cde_street_dir_suffix       TEXT,
    cde_res_unit_type           TEXT,
    text_res_unit_nbr           TEXT,
    text_res_city               TEXT,
    cde_res_state               TEXT,
    text_res_zip5               TEXT,
    text_res_zip4               TEXT,
    text_res_carrier_rte        TEXT,
    ind_res_military            TEXT,
    text_mail_address1          TEXT,
    text_mail_address2          TEXT,
    text_mail_address3          TEXT,
    text_mail_address4          TEXT,
    text_mail_city              TEXT,
    cde_mail_state              TEXT,
    text_mail_zip5              TEXT,
    text_mail_zip4              TEXT,
    text_mail_carrier_rte       TEXT,
    ind_mail_military           TEXT,
    ind_mail_foreign            TEXT,
    desc_party                  TEXT,
    precinct_text_name          TEXT,
    precinct_text_designation   TEXT,
    date_of_birth               TEXT,
    date_of_registration        TEXT,
    text_phone_area_code        TEXT,
    text_phone_exchange         TEXT,
    text_phone_last_four        TEXT,
    text_election_code_1        TEXT,
    text_election_code_2        TEXT,
    text_election_code_3        TEXT,
    text_election_code_4        TEXT,
    text_election_code_5        TEXT,
    text_election_code_6        TEXT,
    text_election_code_7        TEXT,
    text_election_code_8        TEXT,
    text_election_code_9        TEXT,
    text_election_code_10       TEXT,
    text_res_physical_address   TEXT,
    polling_place_text_name     TEXT,
    polling_place_text_address1 TEXT,
    polling_place_text_address2 TEXT,
    polling_place_text_address3 TEXT,
    polling_place_text_address4 TEXT,
    polling_place_text_city     TEXT,
    polling_place_cde_state     TEXT,
    polling_place_text_zip5     TEXT,
    polling_place_text_zip4     TEXT,
    district_cc                 TEXT,
    district_cg                 TEXT,
    district_jd                 TEXT,
    district_kr                 TEXT,
    district_ks                 TEXT,
    district_sb                 TEXT,
    district_pt                 TEXT,
    district_sd                 TEXT
);

CREATE TABLE IF NOT EXISTS RAW.kansas_ncoa_data_2023_11_06
(
    input_county                        TEXT,
    input_first_name                    TEXT,
    input_middle_name                   TEXT,
    input_last_name                     TEXT,
    input_suffix                        TEXT,
    input_id                            TEXT,
    input_addressline1                  TEXT,
    input_addressline2                  TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zip_code                      TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

COPY INTO RAW.kansas_voters_2023_11_06
    FROM @VOTER_FILES/kansas/raw_data/file_date=2023_11_06/Statewide1162023.txt
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_DELIMITER = '\t',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '') REPLACE_INVALID_CHARACTERS = TRUE
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
        )
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.kansas_ncoa_data_2023_11_06
    FROM @VOTER_FILES/kansas/ncoa_data/file_date=2023_11_06/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT'

{% endmacro %}