{% macro import_louisiana_voters() %}

CREATE TABLE IF NOT EXISTS RAW.louisiana_raw_data_2023_11_23
(
    jurisdiction_parish                        TEXT,
    jurisdiction_ward                          TEXT,
    jurisdiction_precinct                      TEXT,
    personal_name_prefix                       TEXT,
    personal_first_name                        TEXT,
    personal_middle_name                       TEXT,
    personal_last_name                         TEXT,
    personal_name_suffix                       TEXT,
    residence_house_number                     TEXT,
    residence_house_fraction                   TEXT,
    residence_street_direction                 TEXT,
    residence_street_name                      TEXT,
    residence_apartment_number                 TEXT,
    residence_city                             TEXT,
    residence_state                            TEXT,
    residence_zipcode5                         TEXT,
    residence_zipcode4                         TEXT,
    mail_address1                              TEXT,
    mail_address2                              TEXT,
    mail_city                                  TEXT,
    mail_state                                 TEXT,
    mail_zipcode5                              TEXT,
    mail_zipcode4                              TEXT,
    mail_country                               TEXT,
    jurisdiction_district_appeals_court        TEXT,
    jurisdiction_district_bese                 TEXT,
    jurisdiction_district_city                 TEXT,
    jurisdiction_district_congressional        TEXT,
    jurisdiction_district_district_court       TEXT,
    jurisdiction_district_justice_of_the_peace TEXT,
    jurisdiction_district_police_jury          TEXT,
    jurisdiction_district_public_service       TEXT,
    jurisdiction_district_representative       TEXT,
    jurisdiction_district_school_board         TEXT,
    jurisdiction_district_senate               TEXT,
    jurisdiction_district_supreme_court        TEXT,
    jurisdiction_district_tax_ward             TEXT,
    personal_sex                               TEXT,
    personal_race                              TEXT,
    registration_political_party_code          TEXT,
    personal_age                               TEXT,
    registration_voter_status                  TEXT,
    registration_date                          TEXT,
    registration_number                        TEXT,
    personal_phone                             TEXT,
    last_voted                                 TEXT,
    residence_walklistorder                    TEXT,
    personal_nameorder                         TEXT,
    voting_history_election_0                  TEXT,
    voting_history_parish_0                    TEXT,
    voting_history_election_1                  TEXT,
    voting_history_parish_1                    TEXT,
    voting_history_election_2                  TEXT,
    voting_history_parish_2                    TEXT,
    voting_history_election_3                  TEXT,
    voting_history_parish_3                    TEXT,
    voting_history_election_4                  TEXT,
    voting_history_parish_4                    TEXT,
    voting_history_election_5                  TEXT,
    voting_history_parish_5                    TEXT,
    voting_history_election_6                  TEXT,
    voting_history_parish_6                    TEXT,
    voting_history_election_7                  TEXT,
    voting_history_parish_7                    TEXT,
    voting_history_election_8                  TEXT,
    voting_history_parish_8                    TEXT,
    voting_history_election_9                  TEXT,
    voting_history_parish_9                    TEXT,
    voting_history_election_10                 TEXT,
    voting_history_parish_10                   TEXT,
    voting_history_election_11                 TEXT,
    voting_history_parish_11                   TEXT,
    voting_history_election_12                 TEXT,
    voting_history_parish_12                   TEXT,
    voting_history_election_13                 TEXT,
    voting_history_parish_13                   TEXT,
    voting_history_election_14                 TEXT,
    voting_history_parish_14                   TEXT,
    voting_history_election_15                 TEXT,
    voting_history_parish_15                   TEXT,
    voting_history_election_16                 TEXT,
    voting_history_parish_16                   TEXT,
    voting_history_election_17                 TEXT,
    voting_history_parish_17                   TEXT,
    voting_history_election_18                 TEXT,
    voting_history_parish_18                   TEXT,
    voting_history_election_19                 TEXT,
    voting_history_parish_19                   TEXT,
    jurisdiction_district_specials_list        TEXT
);

CREATE TABLE IF NOT EXISTS RAW.louisiana_ncoa_results_2023_11_23
(
    input_jurisdiction_parish           TEXT,
    input_firstname                     TEXT,
    input_middlename                    TEXT,
    input_lastname                      TEXT,
    input_suffix                        TEXT,
    input_addressline1                  TEXT,
    input_addressline2                  TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zipcode                       TEXT,
    input_id                            TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

COPY INTO RAW.louisiana_raw_data_2023_11_23
    FROM @VOTER_FILES/louisiana/raw_data/file_date=2023_11_23/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_DELIMITER = '\t',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.louisiana_ncoa_results_2023_11_23
    FROM @VOTER_FILES/louisiana/ncoa_data/file_date=2023_11_23/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT'

{% endmacro %}