{% macro import_missouri_voters() %}

CREATE TABLE IF NOT EXISTS RAW.missouri_voters_2023_10_10
(
    county                    TEXT,
    voter_id                  TEXT,
    first_name                TEXT,
    middle_name               TEXT,
    last_name                 TEXT,
    suffix                    TEXT,
    house_number              TEXT,
    house_suffix              TEXT,
    pre_direction             TEXT,
    street_name               TEXT,
    street_type               TEXT,
    post_direction            TEXT,
    unit_type                 TEXT,
    unit_number               TEXT,
    non_standard_address      TEXT,
    residential_city          TEXT,
    residential_state         TEXT,
    residential_zip_code      TEXT,
    mailing_address           TEXT,
    mailing_city              TEXT,
    mailing_state             TEXT,
    mailing_zip_code          TEXT,
    birthdate                 TEXT,
    political_party           TEXT,
    registration_date         TEXT,
    precinct                  TEXT,
    precinct_name             TEXT,
    split                     TEXT,
    township                  TEXT,
    ward                      TEXT,
    congressional_district_20 TEXT,
    legislative_district_20   TEXT,
    senate_district_20        TEXT,
    voter_status              TEXT,
    voter_history_1           TEXT,
    voter_history_2           TEXT,
    voter_history_3           TEXT,
    voter_history_4           TEXT,
    voter_history_5           TEXT,
    voter_history_6           TEXT,
    voter_history_7           TEXT,
    voter_history_8           TEXT,
    voter_history_9           TEXT,
    voter_history_10          TEXT,
    voter_history_11          TEXT,
    voter_history_12          TEXT,
    voter_history_13          TEXT,
    voter_history_14          TEXT,
    voter_history_15          TEXT,
    voter_history_16          TEXT,
    voter_history_17          TEXT,
    voter_history_18          TEXT,
    voter_history_19          TEXT,
    voter_history_20          TEXT
);

COPY INTO RAW.missouri_voters_2023_10_10 FROM '@VOTER_FILES/missouri/raw_data/file_date=2023_10_10/'
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = '	',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT';


CREATE TABLE IF NOT EXISTS RAW.missouri_ncoa_results_2023_10_10
(
    input_county                        TEXT,
    input_voter_id                      TEXT,
    input_first_name                    TEXT,
    input_middle_name                   TEXT,
    input_last_name                     TEXT,
    input_suffix                        TEXT,
    input_address_line1                 TEXT,
    input_address_line2                 TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zip_code                      TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

COPY INTO RAW.missouri_ncoa_results_2023_10_10 FROM '@VOTER_FILES/missouri/ncoa_data/file_date=2023_10_10/'
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT'


{% endmacro %}
