{% macro import_nebraska_voters() %}


CREATE TABLE IF NOT EXISTS RAW.nebraska_voters_2023_11_01
(
    db_logid                       TEXT,
    cde_registrant_status          TEXT,
    cde_name_title                 TEXT,
    text_name_first                TEXT,
    text_name_middle               TEXT,
    text_name_last                 TEXT,
    cde_name_suffix                TEXT,
    text_registrant_id             TEXT,
    text_res_address_nbr           TEXT,
    text_res_address_nbr_suffix    TEXT,
    cde_street_dir_prefix          TEXT,
    text_street_name               TEXT,
    cde_street_type                TEXT,
    cde_street_dir_suffix          TEXT,
    cde_res_unit_type              TEXT,
    text_res_unit_nbr              TEXT,
    text_res_city                  TEXT,
    cde_res_state                  TEXT,
    text_res_zip5                  TEXT,
    text_res_zip4                  TEXT,
    text_res_carrier_rte           TEXT,
    ind_res_military               TEXT,
    text_mail_address1             TEXT,
    text_mail_address2             TEXT,
    text_mail_address3             TEXT,
    text_mail_address4             TEXT,
    text_mail_city                 TEXT,
    cde_mail_state                 TEXT,
    text_mail_zip5                 TEXT,
    text_mail_zip4                 TEXT,
    text_mail_carrier_rte          TEXT,
    ind_mail_military              TEXT,
    ind_mail_foreign               TEXT,
    desc_party                     TEXT,
    precinct_part_text_name        TEXT,
    precinct_part_text_designation TEXT,
    precinct_text_name             TEXT,
    precinct_text_designation      TEXT,
    birth_year                     TEXT,
    date_of_registration           TEXT,
    text_phone_area_code           TEXT,
    text_phone_exchange            TEXT,
    text_phone_last_four           TEXT,
    text_election_code_1           TEXT,
    text_election_code_2           TEXT,
    text_election_code_3           TEXT,
    text_election_code_4           TEXT,
    text_election_code_5           TEXT,
    text_election_code_6           TEXT,
    text_election_code_7           TEXT,
    text_election_code_8           TEXT,
    text_election_code_9           TEXT,
    text_election_code_10          TEXT,
    text_res_physical_address      TEXT,
    polling_place_text_name        TEXT,
    polling_place_text_address1    TEXT,
    polling_place_text_address2    TEXT,
    polling_place_text_address3    TEXT,
    polling_place_text_address4    TEXT,
    polling_place_text_city        TEXT,
    polling_place_cde_state        TEXT,
    polling_place_text_zip5        TEXT,
    polling_place_text_zip4        TEXT,
    district_aa                    TEXT,
    district_as                    TEXT,
    district_cc                    TEXT,
    district_cd                    TEXT,
    district_cg                    TEXT,
    district_ci                    TEXT,
    district_co                    TEXT,
    district_ed                    TEXT,
    district_fd                    TEXT,
    district_ho                    TEXT,
    district_ja                    TEXT,
    district_jc                    TEXT,
    district_jd                    TEXT,
    district_jj                    TEXT,
    district_js                    TEXT,
    district_lc                    TEXT,
    district_ld                    TEXT,
    district_ma                    TEXT,
    district_nr                    TEXT,
    district_pp                    TEXT,
    district_ps                    TEXT,
    district_rd                    TEXT,
    district_rg                    TEXT,
    district_ri                    TEXT,
    district_sb                    TEXT,
    district_sd                    TEXT,
    district_se                    TEXT,
    district_tw                    TEXT,
    district_ud                    TEXT,
    district_vi                    TEXT,
    district_wa                    TEXT,
    district_we                    TEXT,
    DUP                            TEXT
);

COPY INTO RAW.nebraska_voters_2023_11_01 FROM '@VOTER_FILES/nebraska/raw_data/file_date=2023_11_01/'
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_DELIMITER = '\t',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', ''),
        ENCODING = 'ISO-8859-1'
        )
    ON_ERROR = 'ABORT_STATEMENT';

CREATE TABLE IF NOT EXISTS RAW.nebraska_ncoa_results_2023_11_01
(
    input_first_name                    TEXT,
    input_middle_name                   TEXT,
    input_last_nname                    TEXT,
    input_suffix                        TEXT,
    input_id                            TEXT,
    input_address_line1                 TEXT,
    input_address_line2                 TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zip_code5                     TEXT,
    input_zip_code4                     TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

COPY INTO RAW.nebraska_ncoa_results_2023_11_01 FROM '@VOTER_FILES/nebraska/ncoa_data/file_date=2023_11_01/'
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT'


{% endmacro %}
