{% macro import_ohio_voters() %}

CREATE TABLE IF NOT EXISTS RAW.ohio_voters_2023_09_25
(
    sos_voterid                   TEXT,
    county_number                 TEXT,
    county_id                     TEXT,
    last_name                     TEXT,
    first_name                    TEXT,
    middle_name                   TEXT,
    suffix                        TEXT,
    date_of_birth                 TEXT,
    registration_date             TEXT,
    voter_status                  TEXT,
    party_affiliation             TEXT,
    residential_address1          TEXT,
    residential_secondary_addr    TEXT,
    residential_city              TEXT,
    residential_state             TEXT,
    residential_zip               TEXT,
    residential_zip_plus4         TEXT,
    residential_country           TEXT,
    residential_postalcode        TEXT,
    mailing_address1              TEXT,
    mailing_secondary_address     TEXT,
    mailing_city                  TEXT,
    mailing_state                 TEXT,
    mailing_zip                   TEXT,
    mailing_zip_plus4             TEXT,
    mailing_country               TEXT,
    mailing_postal_code           TEXT,
    career_center                 TEXT,
    city                          TEXT,
    city_school_district          TEXT,
    county_court_district         TEXT,
    congressional_district        TEXT,
    court_of_appeals              TEXT,
    edu_service_center_district   TEXT,
    exempted_vill_school_district TEXT,
    library                       TEXT,
    local_school_district         TEXT,
    municipal_court_district      TEXT,
    precinct_name                 TEXT,
    precinct_code                 TEXT,
    state_board_of_education      TEXT,
    state_representative_district TEXT,
    state_senate_district         TEXT,
    township                      TEXT,
    village                       TEXT,
    ward                          TEXT,
    primary_2000_03_07            TEXT,
    general_2000_11_07            TEXT,
    special_2001_05_08            TEXT,
    general_2001_11_06            TEXT,
    primary_2002_05_07            TEXT,
    general_2002_11_05            TEXT,
    special_2003_05_06            TEXT,
    general_2003_11_04            TEXT,
    primary_2004_03_02            TEXT,
    general_2004_11_02            TEXT,
    special_2005_02_08            TEXT,
    primary_2005_05_03            TEXT,
    primary_2005_09_13            TEXT,
    general_2005_11_08            TEXT,
    special_2006_02_07            TEXT,
    primary_2006_05_02            TEXT,
    general_2006_11_07            TEXT,
    primary_2007_05_08            TEXT,
    primary_2007_09_11            TEXT,
    general_2007_11_06            TEXT,
    primary_2007_11_06            TEXT,
    general_2007_12_11            TEXT,
    primary_2008_03_04            TEXT,
    primary_2008_10_14            TEXT,
    general_2008_11_04            TEXT,
    general_2008_11_18            TEXT,
    primary_2009_05_05            TEXT,
    primary_2009_09_08            TEXT,
    primary_2009_09_15            TEXT,
    primary_2009_09_29            TEXT,
    general_2009_11_03            TEXT,
    primary_2010_05_04            TEXT,
    primary_2010_07_13            TEXT,
    primary_2010_09_07            TEXT,
    general_2010_11_02            TEXT,
    primary_2011_05_03            TEXT,
    primary_2011_09_13            TEXT,
    general_2011_11_08            TEXT,
    primary_2012_03_06            TEXT,
    general_2012_11_06            TEXT,
    primary_2013_05_07            TEXT,
    primary_2013_09_10            TEXT,
    primary_2013_10_01            TEXT,
    general_2013_11_05            TEXT,
    primary_2014_05_06            TEXT,
    general_2014_11_04            TEXT,
    primary_2015_05_05            TEXT,
    primary_2015_09_15            TEXT,
    general_2015_11_03            TEXT,
    primary_2016_03_15            TEXT,
    general_2016_06_07            TEXT,
    primary_2016_09_13            TEXT,
    general_2016_11_08            TEXT,
    primary_2017_05_02            TEXT,
    primary_2017_09_12            TEXT,
    general_2017_11_07            TEXT,
    primary_2018_05_08            TEXT,
    general_2018_08_07            TEXT,
    general_2018_11_06            TEXT,
    primary_2019_05_07            TEXT,
    primary_2019_09_10            TEXT,
    general_2019_11_05            TEXT,
    primary_2020_03_17            TEXT,
    general_2020_11_03            TEXT,
    primary_2021_05_04            TEXT,
    primary_2021_08_03            TEXT,
    primary_2021_09_14            TEXT,
    general_2021_11_02            TEXT,
    primary_2022_05_03            TEXT,
    primary_2022_08_02            TEXT,
    general_2022_11_08            TEXT,
    special_2023_02_28            TEXT,
    primary_2023_05_02            TEXT,
    special_2023_08_08            TEXT
);

CREATE TABLE IF NOT EXISTS RAW.ohio_ncoa_results_2023_09_25
(
    input_id                            TEXT,
    input_county_id                     TEXT,
    input_first_name                    TEXT,
    input_middle_name                   TEXT,
    input_last_name                     TEXT,
    input_suffix                        TEXT,
    input_date_of_birth                 TEXT,
    input_residential_address1          TEXT,
    input_residential_secondary_addr    TEXT,
    input_residential_city              TEXT,
    input_residential_state             TEXT,
    input_residential_zip               TEXT,
    input_residential_country           TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

COPY INTO RAW.ohio_voters_2023_09_25
    FROM @VOTER_FILES/ohio/dt=2023-09-25/raw-data/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', ''),
        REPLACE_INVALID_CHARACTERS = TRUE
        )
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.ohio_ncoa_results_2023_09_25
    FROM @VOTER_FILES/ohio/dt=2023-09-25/ncoa_data/ncoa_results.csv
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT'

{% endmacro %}