{% macro import_tennessee_voters() %}


CREATE TABLE IF NOT EXISTS RAW.tennessee_voters_2024_01_01
(
    county            TEXT,
    voter_id          TEXT,
    registration_date TEXT,
    reg_year          TEXT,
    reg_month         TEXT,
    reg_day           TEXT,
    birth_date        TEXT,
    birth_year        TEXT,
    birth_month       TEXT,
    birth_day         TEXT,
    gender            TEXT,
    race              TEXT,
    last_name         TEXT,
    first_name        TEXT,
    middle_name       TEXT,
    name_suffix       TEXT,
    status            TEXT,
    res_address1      TEXT,
    res_address2      TEXT,
    res_city          TEXT,
    res_state         TEXT,
    res_zip1          TEXT,
    res_zip2          TEXT,
    precinct          TEXT,
    tn_senate         TEXT,
    tn_house          TEXT,
    us_congress       TEXT,
    judicial          TEXT,
    county_district   TEXT,
    ward              TEXT,
    nbr_co_id         TEXT,
    nbr_vo_id         TEXT,
    nov_22_how        TEXT,
    aug_22_party      TEXT,
    aug_22_how        TEXT,
    may_22_party      TEXT,
    may_22_how        TEXT,
    nov_20_how        TEXT,
    aug_20_party      TEXT,
    aug_20_how        TEXT,
    mar_20_party      TEXT,
    mar_20_how        TEXT,
    nov_18_how        TEXT,
    aug_18_party      TEXT,
    aug_18_how        TEXT,
    may_18_party      TEXT,
    may_18_how        TEXT,
    nov_16_how        TEXT,
    aug_16_party      TEXT,
    aug_16_how        TEXT,
    mar_16_party      TEXT,
    mar_16_how        TEXT,
    nov_14_how        TEXT,
    aug_14_party      TEXT,
    aug_14_how        TEXT,
    may_14_party      TEXT,
    may_14_how        TEXT,
    nov_12_how        TEXT,
    aug_12_party      TEXT,
    aug_12_how        TEXT,
    mar_12_party      TEXT,
    mar_12_how        TEXT,
    nov_10_how        TEXT,
    aug_10_party      TEXT,
    aug_10_how        TEXT,
    may_10_party      TEXT,
    may_10_how        TEXT,
    nov_08_how        TEXT,
    aug_08_party      TEXT,
    aug_08_how        TEXT,
    feb_08_party      TEXT,
    feb_08_how        TEXT,
    nov_06_how        TEXT,
    aug_06_party      TEXT,
    aug_06_how        TEXT,
    may_06_party      TEXT,
    may_06_how        TEXT,
    nov_04_how        TEXT,
    aug_04_party      TEXT,
    aug_04_how        TEXT,
    feb_04_party      TEXT,
    feb_04_how        TEXT,
    nov_02_how        TEXT,
    aug_02_party      TEXT,
    aug_02_how        TEXT,
    may_02_party      TEXT,
    may_02_how        TEXT,
    nov_00_how        TEXT,
    aug_00_party      TEXT,
    aug_00_how        TEXT,
    mar_00_party      TEXT,
    mar_00_how        TEXT
);

COPY INTO RAW.tennessee_voters_2024_01_01 FROM '@VOTER_FILES/tennessee/raw_data/file_date=2024_01_01/'
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', ''), ENCODING = 'ISO-8859-1'
        )
    ON_ERROR = 'ABORT_STATEMENT';


CREATE TABLE IF NOT EXISTS RAW.tennessee_ncoa_results_2024_01_01
(
    input_county                        TEXT,
    input_voter_id                      TEXT,
    input_last_name                     TEXT,
    input_first_name                    TEXT,
    input_middle_name                   TEXT,
    input_name_suffix                   TEXT,
    input_address_line1                 TEXT,
    input_address_line2                 TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zip_code5                     TEXT,
    input_zip_code4                     TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

COPY INTO RAW.tennessee_ncoa_results_2024_01_01 FROM '@VOTER_FILES/tennessee/ncoa_data/file_date=2024_01_01/'
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ('NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT'


{% endmacro %}
