{% macro import_wisconsin_voters() %}

CREATE TABLE IF NOT EXISTS RAW.wisconsin_voters_2023_10_17
(
    voter_reg_number           TEXT,
    lastname                   TEXT,
    first_name                 TEXT,
    middle_name                TEXT,
    suffix                     TEXT,
    phone_number               TEXT,
    email_address              TEXT,
    address1                   TEXT,
    address2                   TEXT,
    mailing_address1           TEXT,
    mailing_address2           TEXT,
    mailing_city_state_zip     TEXT,
    house_number               TEXT,
    street_name                TEXT,
    unit_type                  TEXT,
    unit_number                TEXT,
    zipcode                    TEXT,
    jurisdiction               TEXT,
    district_combo             TEXT,
    ward                       TEXT,
    congressional              TEXT,
    state_senate               TEXT,
    state_assembly             TEXT,
    court_of_appeals           TEXT,
    multi_jurisdictional_judge TEXT,
    county                     TEXT,
    county_supervisory         TEXT,
    municipality               TEXT,
    aldermanic                 TEXT,
    school                     TEXT,
    high_school                TEXT,
    sanitary                   TEXT,
    technical_college          TEXT,
    representational_school    TEXT,
    state                      TEXT,
    district_attorney          TEXT,
    circuit_court              TEXT,
    first_class_school         TEXT,
    incorporation              TEXT,
    voter_status               TEXT,
    voter_status_reason        TEXT,
    registration_date          TEXT,
    application_source         TEXT,
    is_permanent_absentee      TEXT,
    voter_type                 TEXT,
    july2023                   TEXT,
    april2023                  TEXT,
    february2023               TEXT,
    november2022               TEXT,
    august2022                 TEXT,
    april2022                  TEXT,
    february2022               TEXT,
    july2021                   TEXT,
    june2021                   TEXT,
    april2021                  TEXT,
    february2021               TEXT,
    november2020               TEXT,
    august2020                 TEXT,
    may2020                    TEXT,
    april2020                  TEXT,
    february2020               TEXT,
    april2019                  TEXT,
    february2019               TEXT,
    november2018               TEXT,
    october2018                TEXT,
    august2018                 TEXT,
    june2018                   TEXT,
    may2018                    TEXT,
    april2018                  TEXT,
    february2018               TEXT,
    january2018                TEXT,
    december2017               TEXT,
    april2017                  TEXT,
    february2017               TEXT,
    november2016               TEXT,
    august2016                 TEXT,
    april2016                  TEXT,
    february2016               TEXT,
    december2015               TEXT,
    november2015               TEXT,
    october2015                TEXT,
    september2015              TEXT,
    july2015                   TEXT,
    june2015                   TEXT,
    may2015                    TEXT,
    april2015                  TEXT,
    february2015               TEXT,
    november2014               TEXT,
    october2014                TEXT,
    september2014              TEXT,
    august2014                 TEXT,
    may2014                    TEXT,
    april2014                  TEXT,
    february2014               TEXT,
    december2013               TEXT,
    november2013               TEXT,
    october2013                TEXT,
    september2013              TEXT,
    may2013                    TEXT,
    april2013                  TEXT,
    february2013               TEXT,
    december2012               TEXT,
    november2012               TEXT,
    august2012                 TEXT,
    june2012                   TEXT,
    may2012                    TEXT,
    april2012                  TEXT,
    february2012               TEXT,
    november2011               TEXT,
    october2011                TEXT,
    august2011                 TEXT,
    july2011                   TEXT,
    may2011                    TEXT,
    april2011                  TEXT,
    february2011               TEXT,
    november2010               TEXT,
    september2010              TEXT,
    april2010                  TEXT,
    february2010               TEXT,
    april2009                  TEXT,
    february2009               TEXT,
    november2008               TEXT,
    september2008              TEXT,
    april2008                  TEXT,
    february2008               TEXT,
    april2007                  TEXT,
    february2007               TEXT,
    november2006               TEXT,
    september2006              TEXT,
    april2006                  TEXT,
    february2006               TEXT
);

CREATE TABLE IF NOT EXISTS RAW.wisconsin_ncoa_results_2023_10_17
(
    input_id                            TEXT,
    input_lastname                      TEXT,
    input_firstname                     TEXT,
    input_middlename                    TEXT,
    input_suffix                        TEXT,
    input_address1                      TEXT,
    input_city                          TEXT,
    input_state                         TEXT,
    input_zipcode                       TEXT,
    input_county                        TEXT,
    household_position                  TEXT,
    name_id                             TEXT,
    individual_record_id                TEXT,
    first_name                          TEXT,
    last_name                           TEXT,
    company_name                        TEXT,
    street_number                       TEXT,
    street_pre_direction                TEXT,
    street_name                         TEXT,
    street_post_direction               TEXT,
    street_suffix                       TEXT,
    unit_type                           TEXT,
    unit_number                         TEXT,
    box_number                          TEXT,
    city_name                           TEXT,
    state_code                          TEXT,
    postal_code                         TEXT,
    postal_code_extension               TEXT,
    carrier_route                       TEXT,
    address_status                      TEXT,
    error_number                        TEXT,
    address_type                        TEXT,
    delivery_point                      TEXT,
    check_digit                         TEXT,
    delivery_point_verification         TEXT,
    delivery_point_verification_notes   TEXT,
    vacant                              TEXT,
    congressional_district_code         TEXT,
    area_code                           TEXT,
    latitude                            TEXT,
    longitude                           TEXT,
    time_zone                           TEXT,
    county_name                         TEXT,
    county_fips                         TEXT,
    state_fips                          TEXT,
    barcode                             TEXT,
    locatable_address_conversion_system TEXT,
    line_of_travel                      TEXT,
    ascending_or_descending             TEXT,
    move_applied                        TEXT,
    move_type                           TEXT,
    move_date                           TEXT,
    move_distance                       TEXT,
    match_flag                          TEXT,
    nxi                                 TEXT,
    ank                                 TEXT,
    residential_delivery_indicator      TEXT,
    record_type                         TEXT,
    country_code                        TEXT,
    address_line_1                      TEXT,
    address_line_2                      TEXT,
    address_id                          TEXT,
    household_id                        TEXT,
    individual_id                       TEXT
);

CREATE TABLE IF NOT EXISTS RAW.wisconsin_voter_history_2023_10_17
(
    county               TEXT,
    voter_id             TEXT,
    election_date        TEXT,
    election_description TEXT,
    vote_method          TEXT,
    party                TEXT
);



COPY INTO RAW.wisconsin_voters_2023_10_17
    FROM @VOTER_FILES/wisconsin/raw_data/file_date=2023_10_17/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.wisconsin_ncoa_results_2023_10_17
    FROM @VOTER_FILES/wisconsin/ncoa_data/file_date=2023_10_17/
    FILE_FORMAT = (
        TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', FIELD_DELIMITER = ',',
        SKIP_HEADER = 1, ESCAPE_UNENCLOSED_FIELD = NONE, TRIM_SPACE = TRUE,
        EMPTY_FIELD_AS_NULL = TRUE, NULL_IF = ( 'NULL', '')
        )
    ON_ERROR = 'ABORT_STATEMENT'

{% endmacro %}