SELECT '2023-11-14'::date                             as FILE_DATE,
       'WY'                                           as STATE_CODE,
       TRIM(COUNTY, '"')                              as COUNTY_CODE,
       TRIM(VOTER_ID, '"')                            AS VOTER_ID,
       NULL                                           AS PREFIX,
       TRIM(FIRST_NAME, '"')                          AS FIRST_NAME,
       TRIM(MIDDLE_NAME, '"')                         AS MIDDLE_NAME,
       TRIM(LAST_NAME, '"')                           AS LAST_NAME,
       TRIM(NAME_SUFFIX, '"')                         AS NAME_SUFFIX,
       TRIM(DETAILS_RA_, '"')                         AS RESIDENCE_ADDRESS_LINE_1,
       NULL                                           AS RESIDENCE_ADDRESS_LINE_2,
       TRIM(CITY_RA_, '"')                            AS RESIDENCE_ADDRESS_CITY,
       'WY'                                           AS RESIDENCE_ADDRESS_STATE,
       TRIM(ZIP_RA_, '"')                             AS RESIDENCE_ADDRESS_ZIPCODE,
       'USA'                                          AS RESIDENCE_ADDRESS_COUNTRY,
       NULL                                           AS BIRTH_YEAR,
       NULL                                           AS BIRTH_MONTH,
       NULL                                           AS BIRTH_DATE,
       'A'                                            as VOTER_STATUS,
       TO_DATE(TRIM(EFF_REG_DATE, '"'), 'MM/DD/YYYY') AS REGISTRATION_DATE,
       NULL                                           AS LAST_VOTED_DATE,
       TRIM(POLITICAL_PARTY, '"')                     AS LAST_PARTY_VOTED,
       NULL                                           AS CONGRESSIONAL_DISTRICT,
       TRIM(SENATE, '"')                              AS STATE_SENATE_DISTRICT,
       TRIM(HOUSE, '"')                               AS STATE_HOUSE_DISTRICT,
       NULL                                           AS JUDICIAL_DISTRICT,
       NULL                                           AS COUNTY_COMMISSION_DISTRICT,
       NULL                                           AS SCHOOL_BOARD_DISTRICT,
       NULL                                           AS CITY_COUNCIL_DISTRICT,
       TRIM(PRECINCT, '"')                            AS COUNTY_PRECINCT,
       NULL                                           AS MUNICIPAL_PRECINCT,
       NULL                                           AS RACE,
       NULL                                           AS GENDER,
       NULL                                           AS MAILING_ADDRESS_LINE_1,
       NULL                                           AS MAILING_ADDRESS_LINE_2,
       NULL                                           AS MAILING_LINE_3,
       NULL                                           AS MAILING_CITY,
       NULL                                           AS MAILING_STATE,
       NULL                                           AS MAILING_ZIPCODE,
       NULL                                           AS MAILING_COUNTRY
FROM DBT_VOTER_DATA.raw.WYOMING_VOTERS_2023_11_14