version: 2
sources:
  - name: raw
    description: This is the raw voter data that is loaded into tables
    tables:
      - name: ALABAMA_NCOA_RESULTS_2024_01_15
      - name: ALASKA_NCOA_RESULTS_2023_11_13
      - name: ARIZONA_NCOA_RESULTS_2023_11_05
      - name: ARKANSAS_NCOA_RESULTS_2023_09_01
      - name: CALIFORNIA_NCOA_RESULTS_2024_02_05
      - name: COLORADO_NCOA_RESULTS_2023_11_30
      - name: CONNECTICUT_NCOA_RESULTS_2023_10_12
      - name: DELAWARE_NCOA_RESULTS_2023_11_17
      - name: DISTRICT_OF_COLUMBIA_NCOA_RESULTS_2023_03_10
      - name: FLORIDA_NCOA_RESULT_2023_08_08
      - name: GEORGIA_NCOA_DATA_2023_09_13
      - name: IDAHO_NCOA_RESULTS_2023_10_26
      - name: IOWA_NCOA_DATA_2023_12_14
      - name: KANSAS_NCOA_DATA_2023_11_06
      - name: LOUISIANA_NCOA_RESULTS_2023_11_23
      - name: MARYLAND_NCOA_RESULTS_2023_12_05
      - name: MICHIGAN_NCOA_DATA_2023_11_21
      - name: MISSISSIPPI_NCOA_RESULTS_2023_12_11
      - name: MISSOURI_NCOA_RESULTS_2023_10_10
      - name: MONTANA_NCOA_RESULTS_2023_11_06
      - name: NEBRASKA_NCOA_RESULTS_2023_11_01
      - name: NEVADA_NCOA_RESULTS_2023_07_31
      - name: NEW_HAMPSHIRE_NCOA_RESULTS_2023_12_04
      - name: NEW_JERSEY_NCOA_RESULTS_2023_11_24
      - name: NEW_MEXICO_NCOA_RESULTS_2023_11_17
      - name: NEW_YORK_NCOA_RESULTS_2023_09_20
      - name: NORTH_CAROLINA_NCOA_RESULTS_2023_07_21
      - name: OHIO_NCOA_RESULTS_2023_09_25
      - name: OKLAHOMA_NCOA_RESULTS_2023_09_23
      - name: OREGON_NCOA_RESULTS_2023_11_01
      - name: PENNSYLVANIA_NCOA_RESULTS_2023_11_13
      - name: RHODE_ISLAND_NCOA_RESULTS_2023_11_16
      - name: SOUTH_CAROLINA_NCOA_RESULTS_2024_01_04
      - name: SOUTH_DAKOTA_NCOA_RESULTS_2023_11_06
      - name: TENNESSEE_NCOA_RESULTS_2024_01_01
      - name: TEXAS_NCOA_RESULTS_2023_11_28
      - name: UTAH_NCOA_RESULTS_2023_11_06
      - name: VERMONT_NCOA_RESULTS_2023_09_27
      - name: VIRGINIA_NCOA_RESULTS_2023_11_17
      - name: WASHINGTON_NCOA_RESULTS_2023_09_01
      - name: WEST_VIRGINIA_NCOA_RESULTS_2023_11_06
      - name: WISCONSIN_NCOA_RESULTS_2023_10_17
      - name: WYOMING_NCOA_RESULTS_2023_11_14
